version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    environment:
      - GIN_PORT=8080

  redis:
    image: redis:7-alpine
    volumes:
      - ./data/redis:/data